//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DroneBatteryLoadCalculator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DroneBatteryLoadCalculator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oblicz czas ładowania akumulatora Twojego drona.
        /// </summary>
        internal static string button1_text {
            get {
                return ResourceManager.GetString("button1_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozpocznij ładowanie.
        /// </summary>
        internal static string button2_text {
            get {
                return ResourceManager.GetString("button2_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ustawienia ręczne.
        /// </summary>
        internal static string combo_box1_ustawienia_reczne {
            get {
                return ResourceManager.GetString("combo_box1_ustawienia_reczne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dron:.
        /// </summary>
        internal static string dron {
            get {
                return ResourceManager.GetString("dron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  % musisz ładować przez .
        /// </summary>
        internal static string musisz_ladowac1 {
            get {
                return ResourceManager.GetString("musisz_ladowac1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj % do naładowania:.
        /// </summary>
        internal static string podaj_procent_do_naladowania {
            get {
                return ResourceManager.GetString("podaj_procent_do_naladowania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sek.
        /// </summary>
        internal static string sek {
            get {
                return ResourceManager.GetString("sek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wprowadź wartość będącą liczbą.
        /// </summary>
        internal static string wprowadz_liczbe1 {
            get {
                return ResourceManager.GetString("wprowadz_liczbe1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wprowadź liczbę, będącą udziałem procentowym baterii do naładowania.
        /// </summary>
        internal static string wprowadz_tekst1 {
            get {
                return ResourceManager.GetString("wprowadz_tekst1", resourceCulture);
            }
        }
    }
}
